### PR TITLE
addimages

### PR DESCRIPTION
**Pull request by MjNikoff**
Added images

### CODE REVIEW

**Comment by MjNikoff** [comment]
Added 10 images with cats and 10images with  other objects

**Comment by Artem-Gulyaev** [comment]
Cool images =)

**Comment by Artem-Gulyaev** [comment]
Not joking)

**Comment by Artem-Gulyaev** [comment]
Btw, it is useful to use inkscape or any other vector editor to make the images available in various scales without mandatory loose of quality.

**Pull request merged**
